baseURL = 'yassine-safraoui.github.io/'
languageCode = 'en-us'
title = 'Yassine Safraoui Portfolio'
theme = 'hugo-profile'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/microsoft-clarity'
